### ISSUE TITLE
Ingredient parsing issue: "6 (1/4 inch thick) slices" parsed as "4 inch thick slices" on allrecipes

### ISSUE THREAD

**Issue by Thra11** [openculinary/ingreedy-py#11]
**Describe the bug**
I found a recipe that had failed to parse the ingredient quantity correctly.

**To Reproduce**
1. Look at [this recipe page on RecipeRadar](https://www.reciperadar.com/#search&action=view&id=RA6FKVR9Tadeoy8KxiwnFz6bJVme1ZC1dsac). See that it requires "4 inch thick) slices Italian **bread**..."
3. Click through to the [original recipe](https://www.allrecipes.com/recipe/111236/tubbys-pesto-panini/): It actually requires "6 (1/4 inch thick) slices Italian bread"

**Expected behavior**
It should magically know that "6" is the quantity and "1/4 inch thick" is an adjectival phrase / part of the ingredient description. I don't know what the best way to do this is. Perhaps the `(` (character which isn't a quantity or unit) is a good hint that that's where the quantity ends and the description starts? (I assume `(` is ignored?)

Now should I make this with 4x inch-thick slices, or one 4-inch-thick slice...?

**Comment by jayaddison** [comment]
Thank you @Thra11!  I've moved this across to the `ingreedy-py` library where I think this bug is most likely to originate.

We can hopefully handle this by appending a new a test case - similar to [this one in the `ingreedytest.py`](https://github.com/openculinary/ingreedy-py/blob/c23acc093495e28e4c65168c12cfb75dbde44219/ingreedytest.py#L153-L159) - and then updating the parser [grammar](https://github.com/openculinary/ingreedy-py/blob/c23acc093495e28e4c65168c12cfb75dbde44219/ingreedypy.py#L65-L377) to get all the tests to pass (ideally without making the grammar much more complex).

Would you have any interest in attempting to add the test case and/or fix?

**Comment by Thra11** [comment]
I've added a couple of test cases and my attempt at a fix. Let me know if you have suggestions for changes, or feel free to take the test cases and write your own grammar fix if you'd prefer to do it in a different way.

**Comment by jayaddison** [comment]
That's excellent, thanks @Thra11.  The tests prove the behaviour here and the grammar stays equally comprehensible, I think.  The only adjustment I might make would be to update one or two of the rule names, but I'm not sure what names to suggest instead yet.  I'll merge this soon either way.

**Comment by Thra11** [comment]
> update one or two of the rule names,

I assume you're referring to `thing` and `parenthesized_stuff`? If so, I totally agree. It was getting late and I couldn't decide exactly what the correct terms should be.

**Comment by Thra11** [comment]
> I've moved this across to the ingreedy-py library where I think this bug is most likely to originate.

Slightly offtopic but if you are intending to welcome bug reports from outsiders, you might want to have a central location for logging issues so people aren't guessing which component it applies to.

**Comment by jayaddison** [comment]
> > update one or two of the rule names,
> 
> I assume you're referring to `thing` and `parenthesized_stuff`? If so, I totally agree. It was getting late and I couldn't decide exactly what the correct terms should be.

Yep, I was - and no worries, I know the feeling :)

> Slightly offtopic but if you are intending to welcome bug reports from outsiders, you might want to have a central location for logging issues so people aren't guessing which component it applies to.

That's a good idea.  I'll have a think about how to configure that.  To be honest most 'initial issue report' items could arrive at the `openculinary` organization level before being moved to the relevant repository/repositories.  I'm not sure how feasible that is in GitHub though.

**Comment by jayaddison** [comment]
Resolved by #13.
